#!/usr/bin/env bash



# Mostrar los puertos TCP en escucha
echo "Puertos TCP en escucha:"
ss -tnlp | awk '/^tcp/ {print $4, $6}' | awk -F '[ :]+' '{print $5, $NF}' | tail -n +2

# Mostrar los puertos UDP en escucha
echo "Puertos UDP en escucha:"
ss -unlp | awk '/^udp/ {print $4, $6}' | awk -F '[ :]+' '{print $5, $NF}' | tail -n +2
