#!/usr/bin/bash


# Mostrar los puertos TCP en escucha
echo "Puertos TCP en escucha:"
ss -tlnp | awk '/^tcp/ {print $4, $NF}' | awk -F '[:/]' '{print $2, $NF}'

# Mostrar los puertos UDP en escucha
echo "Puertos UDP en escucha:"
ss -ulnp | awk '/^udp/ {print $4, $NF}' | awk -F '[:/]' '{print $2, $NF}'
