#!/usr/bin/env bash

# Display listening TCP ports
echo "Puertos TCP en escucha:"
ss -tnlp | awk '/^tcp/ {print $4, $6}' | awk -F '[ :]+' '{print $5, $NF}' | tail -n +2

# Display listening UDP ports
echo "Puertos UDP en escucha:"
ss -unlp | awk '/^udp/ {print $4, $6}' | awk -F '[ :]+' '{print $5, $NF}' | tail -n +2
